CREATE TABLE clientes (
  CodigoCli INT NOT NULL AUTO_INCREMENT,
  NomeCli VARCHAR(100) NOT NULL,
  EnderecoCli VARCHAR(255) NOT NULL,
  CodigoCid INT NOT NULL,
  EmailCli VARCHAR(45) NOT NULL,
  DataNCli DATE NOT NULL,
  TelefoneCli VARCHAR(15) NOT NULL,
  CPFCli VARCHAR(14) NOT NULL,
  PRIMARY KEY (CodigoCli),
  INDEX FL_CodigoCid_idx (CodigoCid) VISIBLE,
  CONSTRAINT FK_CodigoCid FOREIGN KEY (CodigoCid) REFERENCES cidades (codigo_cid) ON DELETE NO ACTION ON UPDATE NO ACTION
);